### ISSUE TITLE
Stivbot usage

### ISSUE THREAD

**Issue by LucBerge** [Or4cl3AI/Or4cl3AI#2]
Hello @Or4cl3AI,

I see you seamed interested about [Stivbot](https://github.com/stivbot/stivbot) and you (tried to) use it [here](https://github.com/Or4cl3AI/AutoDevAImobile/issues/2). I would like to better understand what were you expectations will installing it?

**Comment by Or4cl3AI** [comment]
@LucBerge I apologize for that I didn't actually know how any of this worked at that point and didn't use it properly but now that I understand it I'm gonna set up another repository for it

**Comment by LucBerge** [comment]
Well, it has nothing to deal, with what you are building: [GitBotAI](https://github.com/Or4cl3AI/GitBotAI-2.0). No competition here 😄 

It is a bot to help users build their business ideas, compare their ideas and identify the most promising one.

**Comment by Or4cl3AI** [comment]
Yeah I actually have all kinds of business ideas and am kinda trying to get a startup called Or4cl3 AI Solutions up and running

**Comment by LucBerge** [comment]
> am kinda trying to get a startup [...] up and running

Same, new in entrepreneurship as well...

Did you struggled with all your business ideas? Cause I do

**Comment by Or4cl3AI** [comment]
Man thats kind of an understatement I'm sure you can tell by the eclectic range of things I'm working on Im kind of all over the place when it comes to ideas and picking just one to try to use to launch this startup has been fun 

But I do think I have decided on one you should check out my repository for TheAI (pronounced The Eye)

**Comment by LucBerge** [comment]
Having fun with my ideas a well but not sure which one to pick. How did you choose?

Good luck with this one, all security companies are turning to AI. You should have something unique

**Comment by Or4cl3AI** [comment]
Honestly I gave both Googles bard and gpt4 a list with brief descriptions of like 10 of my repositories and had it narrow them down to the 3 most likely to get funded and both of them said either one of my developer tools like AutoCodeAI and AppGenieMobile, mental health support and cyber security with cyber security being the most likely so I went with that one lol

And while there is kind of an over abundance of cyber security solutions out there none of them offer the same level of automated protection that TheAI offers or the level of customization and ease of use real time threat detection and defense etc...

**Comment by Or4cl3AI** [comment]
Go check out the wiki page for TheAI you can see how we set ourselves apart
